### ISSUE TITLE
can you tell me how to restore

### ISSUE THREAD

**Issue by wOo00w** [machv/xhyper-vbackup#2]
Hey bro,I got a problem here,I have backed up the VM using this script.But got trouble restoring it ,So can you have a second to tell me how to restore those Checkpoints? I would be very appreciate it : )

**Comment by machv** [comment]
Hi,
in order to restore a VM from a backup created via this module, you can just import a folder with a backup output with a VM on any Hyper-V host (e. g. via Hyper-V Manager or PowerShell).

I've just updated the repo's README file with a basic intro how to proceed using a PowerShell, you can check that here https://github.com/machv/xhyper-vbackup/blob/master/README.md.

**Comment by wOo00w** [comment]
well done,thank you so much.
